const CONFIG = {
	LIMIT: 50,
	ACTION_ADD_FAV: 'ADD_FAVOURITE',
	ACTION_DEL_FAV: 'DELETE_FAVOURITE',
	ACTION_POKEMONS: 'POKEMONS',
	ACTION_POKEMONS_LOADING: 'POKEMON_LOADING',
	ACTION_POKEMON: 'POKEMON',
	ACTION_POKEMON_LOADING: 'POKEMON_LOADING',
};
export default CONFIG;
